apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-cluster
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 10.2.0  # Use the desired version of the Kafka Helm chart
    chart: kafka
    helm:
      valuesObject:
        zookeeper:
          replicaCount: 3
        replicaCount: 3
        externalAccess:
          enabled: true
          service:
            type: LoadBalancer
        ingress:
          enabled: true
          path: /
          hosts:
            - mydomain.example.com
          annotations:
            kubernetes.io/ingress.class: nginx
            kubernetes.io/tls-acme: "true"
          labels: {}
          tls:
            - secretName: mydomain-tls
              hosts:
                - mydomain.example.com

  destination:
    server: https://kubernetes.default.svc
    namespace: kafka-namespace  # Replace with your desired namespace

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
