apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-cluster
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 17.4.4  # Specify the desired version of the Redis Helm chart
    chart: redis
    helm:
      valuesObject:
        cluster:
          enabled: true
          slaveCount: 2  # Number of slave nodes (total nodes will be 1 master + 2 slaves = 3 nodes)
        usePassword: false  # Set to true if you want to use a password, then specify password in the values

  destination:
    server: https://kubernetes.default.svc
    namespace: redis-namespace  # Replace with your desired namespace

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
